version: '3.5'

services:

  db_service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - $DB_PORT:3306
    restart: unless-stopped
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=docker_php_service
    volumes:
      - ./php_project:/var/www/html
      - ./provision/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#      - ./provision:/tmp
    ports:
      - $PHP_PORT:80
    restart: unless-stopped
    depends_on:
      - db_service
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
