version: '3.5'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./app_project:/usr/app/
      - /usr/app/node_modules
    ports:
      - $NODEJS_PORT:8080
    restart: unless-stopped
