version: '3.5'

services:

  db_service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $DB_NAME
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - $DB_PORT:3306
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  fpm_service:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: php:fpm
    environment:
      PHP_IDE_CONFIG: serverName=docker_php_service
    volumes:
      - ./php_project:/var/www/html
      - ./provision/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#    ports:
#      - $PHP_PORT:80
    restart: unless-stopped
    depends_on:
      - db_service
    tty: true
    networks:
      - app-network

  #Nginx Service
  webserver:
#    image: nginx:alpine
    image: nginx:latest
#    container_name: webserver
    restart: unless-stopped
    depends_on:
      - fpm_service
    tty: true
    ports:
      - $PHP_PORT:80
      - "442:443"
    volumes:
      - ./provision/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
