# FROM python:3.9
FROM python

WORKDIR /usr/src/app

# RUN cat /etc/os-release

# RUN apt-get update
# RUN apt-get install graphviz libgv-python -y

# RUN pip -V

# RUN pip install git+https://github.com/DamnedFacts/rcviz.git

COPY ./ /usr/src/app